In [1]:
import sys
sys.path.append("../ingest-pipeline/src/converters")
sys.path.append("../ingest-pipeline/src/generators")
sys.path.append("../ingest-pipeline/src/")
sys.path.append("./python/")

from DataModel.Atom import Atom, AtomT
from DataModel.Structure import Structure, StructureT
from DataModel.Quaternion import Quaternion, QuaternionT
from DataModel.P import P, PT
from DataModel.AtomicModel import *
from DataModel.Parameters import Parameters, ParametersT

from DataModel.DataClass import DataClass
from DataModel.Datum import Datum, DatumT
from DataModel.Matrix import Matrix, MatrixT
from DataModel.Domain import Domain
from DataModel.DataType import DataType
from DataModel.DataSet import DataSet, DataSetT
from filegroup import *
from transform_generator import *
from ctf_generator import *
from image_generator import *
from dataloader import Dataloader as dl
import matplotlib.pyplot as plt
from datum_helpers import *

import argparse
from clustering_imports import *


from ClusterTreeNode import ClusterTreeNode
from collections import deque
import time
from IPython.display import display
import json
import networkx as nx
from loguru import logger
from graph_support import *
from likelihood_scratch import *
from tree_build import *
from clustering_driver import *


In [2]:
# img_data = lift_datum_buf_to_datumT(extract_datum(DataSet.GetRootAsDataSet(dl.load_flatbuffer("images_0.fbs"),0)))
# print(img_data)
a,b,c = hierarchify_wrapper("../ingest-pipeline/src/output.fbs", 2,100,10)

n,d,p = tree_loader("foo_tree_hierarchy.json")


2023-12-02 08:11:21.221 | INFO     | clustering_driver:hierarchify:64 - 50,9,2,100,10,0.03277562300354475,0.00047686899779364467


50
shorted: 2
1
2
shorted: 2
3
4
shorted: 2
5
6
torch.Size([10, 1, 3, 3])
tensor([  0.0000,  61.1474,  98.8180, 124.0967,  71.9722, 107.8518,  50.5272,
        115.2128, 114.9913,  73.3076])
tensor([ 61.1474,   0.0000,  85.9651, 117.6988,  56.0089,  97.7394,  50.0600,
        109.8590,  99.5992,  68.5347])
tensor([ 98.8180,  85.9651,   0.0000, 134.4805,  80.1810,  62.0403,  98.4784,
         97.8315,  98.0000,  90.9010])
tensor([124.0967, 117.6988, 134.4805,   0.0000,  95.0158, 125.1319, 121.3631,
        108.1111, 151.5487,  89.2637])
tensor([71.9722, 56.0089, 80.1810, 95.0158,  0.0000, 76.3675, 50.5668, 76.3151,
        93.4291, 65.1460])
tensor([107.8518,  97.7394,  62.0403, 125.1319,  76.3675,   0.0000, 101.1187,
         75.5778, 115.0435,  74.6458])
tensor([ 50.5272,  50.0600,  98.4784, 121.3631,  50.5668, 101.1187,   0.0000,
        114.2060, 108.5541,  69.9214])
tensor([115.2128, 109.8590,  97.8315, 108.1111,  76.3151,  75.5778, 114.2060,
          0.0000,  86.1220,  92.6175])


In [12]:
# print(type(d[2].m1))

rc = level_order_search(n, d[2],100)
# print(rc)

tensor([[[81.+0.j],
         [89.+0.j]]])


AttributeError: 'list' object has no attribute 'push_back'