In [1]:
from likelihood_scratch import *

In [1]:
import numpy as np


In [21]:
a = np.load("/home/aroot/stuff/cryoem/Ensemble-reweighting-using-Cryo-EM-particles/processed_images/images_experimental.npy")
avg = np.mean(a)


In [22]:
avg

6.830259227715423e-05

In [23]:
total = np.sum(np.array([np.square(x - avg) for x in a]))
total


152.29761596701275

In [24]:
noise = np.divide(total, a.shape[0] - 1.0)
noise

0.07440039861602968

In [12]:
total = np.divide(total, a.shape[0])

In [13]:
total

array([[-4.08178405e-06,  4.10250103e-05,  3.51972944e-06, ...,
         2.87493707e-05,  3.43414546e-05,  7.04454914e-05],
       [-5.98882147e-05,  7.14335969e-06,  3.60271628e-05, ...,
         2.69680935e-05,  1.04538801e-04, -7.14660354e-05],
       [ 4.77372326e-05,  4.23026103e-06,  3.83518413e-05, ...,
        -9.49261395e-06, -3.18132679e-05,  5.38777506e-05],
       ...,
       [ 6.98715372e-05,  7.80698244e-05, -4.96938175e-05, ...,
        -2.44640158e-05, -2.86792880e-05, -1.04107999e-04],
       [-3.47192330e-05, -1.33836514e-05,  5.63525088e-05, ...,
        -4.43169704e-05,  1.86856144e-05,  1.24207204e-05],
       [-8.96735787e-05, -2.66879634e-05,  2.26679968e-05, ...,
        -5.13206075e-05,  8.77405895e-05, -5.62979213e-05]])

In [14]:
np.save("mean.npy", total)

In [15]:
total = np.zeros((128,128))
# for i,val in enumerate(a):

In [18]:
mean = np.load("mean.npy")
for i,val in enumerate(a):
  total = total + np.square(val - mean)
sigma_square = total / (a.shape[0] - 1.0)

In [17]:
arr = np.array([[1], [2]])
np.square(arr)

array([[1],
       [4]])

In [19]:
np.save("sigma_square.npy", sigma_square)

In [20]:
sigma_square

array([[4.23557201e-06, 4.54685616e-06, 4.33508338e-06, ...,
        4.65139052e-06, 4.38663112e-06, 4.58068387e-06],
       [4.48444407e-06, 4.23190016e-06, 4.33047635e-06, ...,
        4.54909470e-06, 4.27151061e-06, 4.42317536e-06],
       [4.20346276e-06, 4.50724336e-06, 4.34229671e-06, ...,
        4.31272149e-06, 4.19981895e-06, 4.43499047e-06],
       ...,
       [4.36876096e-06, 4.48609724e-06, 4.39227755e-06, ...,
        4.01075882e-06, 4.26154718e-06, 4.14930082e-06],
       [4.27435197e-06, 4.21972890e-06, 4.19809969e-06, ...,
        4.36550781e-06, 4.30542237e-06, 4.41927886e-06],
       [4.29914618e-06, 4.44823134e-06, 4.38377063e-06, ...,
        4.30844803e-06, 4.44837335e-06, 4.06402130e-06]])